global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
  - job_name: 'app_servers'
    static_configs:
      - targets: ['app:3000', 'app1:3001', 'app2:3002']
